openapi: 3.0.1
info:
  title: '@jupiterone/graph-simplemdm'
  description: A JupiterOne Integration for ingesting data of the SimpleMDM API
  x-cortex-git:
    github:
      repository: JupiterOne/graph-simplemdm
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-simplemdm'
  x-cortex-service-groups:
    - tier-4
